site_name: homestock
site_description: homestock scrapes US Census Bureau data to calculate attainable housing stock for each census tract within a selected county.
site_author: jpepper19
site_url: https://jpepper19.github.io/homestock
repo_url: https://github.com/jpepper19/homestock

copyright: "Copyright © 2024 - 2024 Joshua Pepper"

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
  custom_dir: docs/overrides
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  # - pdf-export
  - mkdocs-jupyter:
      include_source: true
      ignore_h1_titles: true
      execute: true
      allow_errors: false
      ignore:
        - conf.py
      execute_ignore:
        - "*ignore.ipynb"

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Report Issues: https://github.com/jpepper19/homestock/issues
  - Examples:
      - Homestock Example: examples/homestock_example.ipynb
      - Lab 7 Raster & Image: examples/Lab7_Raster_Image_Examples.ipynb
  - API Reference:
      - common module: common.md
      - folium module: folium_map.md
      - homestock module: homestock.md

